exclude: "pyproject.toml|poetry.lock|samples"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        language: system
        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: local
    hooks:
      - id: format
        name: format
        pass_filenames: false
        entry: bash -c "black . && git add -u"
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: lint
        name: lint
        pass_filenames: false
        entry: flakeheaven lint .
        language: python
        types: [python]
