"""Create Log, Vehicle and VehicleToLog table.

Revision ID: a3b7bbf7fb46
Revises: 
Create Date: 2023-01-18 15:23:35.654725

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a3b7bbf7fb46"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timestamp_format", sa.String(length=40), server_default="ISO8601", nullable=False),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("speed_unit", sa.String(length=20), nullable=True),
        sa.Column("odometer", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("odometer_unit", sa.String(length=20), nullable=False),
        sa.Column("state_of_charge", sa.Integer(), nullable=False),
        sa.Column("elevation", sa.Integer(), nullable=False),
        sa.Column("elevation_unit", sa.String(length=20), nullable=False),
        sa.Column("shift_state", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle", sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "vehicle_to_log",
        sa.Column("vehicle_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("log_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["log_id"], ["log.id"], name="vehicle_to_log__log_id_fk"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], name="vehicle_to_log__vehicle_id_fk"),
        sa.PrimaryKeyConstraint("vehicle_id", "log_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_to_log")
    op.drop_table("vehicle")
    op.drop_table("log")
    # ### end Alembic commands ###
