"""Create Log and Vehicle table.

Revision ID: c2c43de6d77f
Revises:
Create Date: 2023-01-18 23:05:48.520106

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c43de6d77f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'log',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('timestamp_format', sa.String(length=40), server_default='ISO8601', nullable=False),
        sa.Column('speed', sa.Integer(), nullable=True),
        sa.Column('speed_unit', sa.String(length=20), nullable=True),
        sa.Column('odometer', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('odometer_unit', sa.String(length=20), nullable=False),
        sa.Column('state_of_charge', sa.Integer(), nullable=False),
        sa.Column('elevation', sa.Integer(), nullable=False),
        sa.Column('elevation_unit', sa.String(length=20), nullable=False),
        sa.Column('shift_state', sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'vehicle',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('log')
    # ### end Alembic commands ###
