"""Rename VehicleLogs soc field name.

Revision ID: 3469f44bc875
Revises: 600af940e35a
Create Date: 2023-01-15 21:43:29.159099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3469f44bc875'
down_revision = '600af940e35a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_logs', sa.Column('state_of_charge', sa.Integer(), nullable=False))
    op.drop_column('vehicle_logs', 'state_of_change')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_logs', sa.Column('state_of_change', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vehicle_logs', 'state_of_charge')
    # ### end Alembic commands ###
