"""Create Vehicle and Vehicle Logs tables.

Revision ID: 600af940e35a
Revises: 
Create Date: 2023-01-15 15:26:26.916746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '600af940e35a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('odometer_unit', sa.String(length=10), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('elevation_unit', sa.String(length=10), nullable=False),
    sa.Column('state_of_change', sa.Integer(), nullable=False),
    sa.Column('shift_state', sa.String(length=1), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('speed_unit', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='vehicle_logs_vehicle_id_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_to_logs',
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['vehicle_logs.id'], name='vehicle_to_logs_vehicle_logs_id_fk'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='vehicle_to_logs_vehicle_id_fk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_to_logs')
    op.drop_table('vehicle_logs')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
